<?php 
include('header.phtml');
include('nav.phtml');
?>
<div class="row">
<div class="small-12 medium-10 medium-offset-1 columns">
	<table class="small-12">
		<tbody>
			<!-- Lists all users if Administrator, only yourself if user -->
			<?php foreach($clients as $client) { ?>	
			<tr>
				<td>
				<h4><span class="name"><?=$client['Name']?></a></h3>
					<p class="description"><?=$client['ClientDescription']?></p>
				</td>
      				<td>
					<a href="clients/disable/<?=$client['UniqueClientID']?>" class="button">Disable</a>
      				</td>
      				<td>
      					<a class="button disabled" title="Disable to remove.">Remove</a>
      				</td>
				
				<td>
				<span class="round radius secondary label" title="Last Seen">Last seen </br><?=gmdate("Y-m-d\ H:i:s \ ", $client['SeenTS']) ?></a>
      				</td>
			</tr>
			<?php } ?>
		</tbody>
	</table>
</div>
</div>
<?php 
include('footer.phtml'); 
?>
