<!DOCTYPE html>
<html>
<head>
	<title>Castcloud Management</title>
	<link rel="stylesheet" href="<?=str_replace("index.php", "", $_SERVER["SCRIPT_NAME"])?>../lib/foundation/css/normalize.css">
	<link rel="stylesheet" href="<?=str_replace("index.php", "", $_SERVER["SCRIPT_NAME"])?>../lib/foundation/css/foundation.css">
	<link rel="stylesheet" href="<?=str_replace("index.php", "", $_SERVER["SCRIPT_NAME"])?>style.css">
</head>
<body>