<?php 
include('header.phtml');
?>
<div class="row">
<div class="small-12 medium-6 medium-offset-3 columns">
	<form action="install" method="POST">
		<fieldset>
			<legend>Database</legend>
			<div class="small-12">
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Username</label>
					</div>
					<div class="small-9 columns">
						<input type="text" id="db-username" placeholder="castcloud" value="castcloud">
					</div>
				</div>
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Password</label>
					</div>
					<div class="small-9 columns">
						<input type="password" id="db-password" placeholder="********">
					</div>
				</div>
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Hostname</label>
					</div>
					<div class="small-9 columns">
						<input type="text" id="db-hostname" placeholder="localhost" value="localhost">
					</div>
				</div>
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Port</label>
					</div>
					<div class="small-9 columns">
						<input type="text" id="db-hostname" placeholder="3306" value="3306">
					</div>
				</div>
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Database</label>
					</div>
					<div class="small-9 columns">
						<input type="text" id="db-hostname" placeholder="castcloud" value="castcloud">
					</div>
				</div>
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Prefix</label>
					</div>
					<div class="small-9 columns">
						<input type="text" id="db-hostname" placeholder="cc_" value="cc_">
					</div>
				</div>
			</div>
		</fieldset>
		<fieldset>
			<legend>Administrator user</legend>
			<div class="small-12">
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Username</label>
					</div>
					<div class="small-9 columns">
						<input type="text" id="cc-username" placeholder="castcloud" value="castcloud">
					</div>
				</div>
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Password</label>
					</div>
					<div class="small-9 columns">
						<input type="password" id="cc-password" placeholder="********">
					</div>
				</div>
		</fieldset>
	</form>
</div>
</div>
<?php 
include('footer.phtml'); 
?>