<?php 
include('header.phtml');
if (isset($_SESSION['login'])) {
	echo $status; 
?>
<form action="logout" method="POST">
<input type="submit" value="Log out">
</form>
<?php 
}
else { 
?>
<div class="row">
	<form action="login" method="POST">
		<div class="small-12 medium-4 medium-offset-4 columns">
			<div class="row">
				<div class="large-12 columns">
					<label>Username:
						<input name="username" type="text">
					</label>
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<label>Password:
						<input name="password" type="password">
					</label>
				</div>
			</div>
			<input type="submit" class="button" value="Log in">
		</div>
	</form>
</div>
<?php 
}
include('footer.phtml'); 
?>