				<nav class="top-bar hide-for-small" data-topbar>
					<ul class="title-area">
						<li class="name">
							<h1><a href="/management/">Castcloud Management</a></h1>
						</li>
						<li class="toggle-topbar menu-icon">
							<a href="#">Menu</a>
						</li>
					</ul>
					
					<section class="top-bar-section">						
						<ul class="right">
							<li class="has-form">
								<form action="logout" method="POST">
									<input type="submit" class="button" value="Log out">
								</form>
							</li>
						</ul>
					</section>
				</nav>
