<?php 
include('header.phtml');
include('nav.phtml');
?>
<div class="row">
<div class="small-12 medium-10 medium-offset-1 columns">
	<div class="row">
		<div class="left"><h3>Welcome <?php echo $_SESSION['username']; ?></h3></div>
	</div>
	<table class="small-12">
		<tbody>
<?php if ($userlevel >= 100) { ?>
			<tr>
				<td colspan="5">
					<a href="adduser" class="button expand">+ Add new user</a>
      			</td>
      		</tr>
<?php } ?>
<?php foreach ($usernames as $value) { ?>
			<tr>
				<td><span class="inline"><a href="edit/<?=$value["username"]?>" class="button"><?=$value["username"]?></a></span></td>
<?php if ($userlevel >= 100) { ?>
				<td>
					<select id="select-userlevel-<?=$value["username"]?>" class="select-userlevel">
						<option value="-1" <?=$value["userlevel"] == -1 ? "selected":""?>>Disabled</option>
						<option value="0" <?=$value["userlevel"] == 0 ? "selected":""?>>User</option>
						<option value="100" <?=$value["userlevel"] == 100 ? "selected":""?>>Administrator</option>
					</select>
      			</td>
<?php } ?>
      			<td>
<?php if ($_SESSION['username'] == $value["username"]){ ?>
      				<a href="manageclients" class="button">Clients</a>
<?php } ?>
      			</td>
      			<td>
<?php if ($_SESSION['username'] == $value["username"]){ ?>
      				<a href="settings" class="button">Settings</a>
<?php } ?>
      			</td>
      			<td>
	  				<a href="export/<?php echo $value["username"]; ?>" class="button">Export</a>
      			</td>
			</tr>
<?php } ?>
		</tbody>
	</table>
</div>
</div>
<?php 
include('footer.phtml'); 
?>
