<?php 
include('header.phtml');
?>
<div class="row">
<div class="small-12 medium-6 medium-offset-3 columns">
	<table>
		<thead>
			<th>Username</th>
			<th>Level</th>
			<th>Actions</th>
		</thead>
		<tbody>
			<tr>
				<td><a href="edit/sjefen6">sjefen6</a></td>
				<td>
					<label>Select Box
						<select>
							<option value="-1">Dsabeled</option>
							<option value="0">User</option>
							<option value="100">Administrator</option>
						</select>
					</label>
      			</td>
      			<td>
      				<a href="export/sjefen6">Export</a>
      			</td>
			</tr>
		</tbody>
	</table>
</div>
</div>
<?php 
include('footer.phtml'); 
?>