<?php 
include('header.phtml');
include('nav.phtml');
?>
<div class="row">
<div class="small-12 medium-10 medium-offset-1 columns">
	<div class="row">
		<div class="left"><h3>Welcome <?php echo $_SESSION['username']; ?></h3></div>
	</div>
	<table>
		<tbody>
			<!-- Lists all users if Administrator, only yourself if user -->
			<tr>
				<td><span class="inline"><a href="edit/sjefen6" class="button">sjefen6</a></span></td>
				<!-- Only for Administrators -->
				<td>
					<select>
						<option value="-1">Disabled</option>
						<option value="0" selected>User</option>
						<option value="100">Administrator</option>
					</select>
      			</td>
      			<!-- end only -->
      			<!-- Should only be shown and accessible for the signed in user -->
      			<td>
      				<a href="export/sjefen6" class="button">Clients</a>
      			</td>
      			<td>
      				<a href="export/sjefen6" class="button">Settings</a>
      			</td>
      			<!-- end only -->
      			<td>
      				<a href="export/sjefen6" class="button">Export</a>
      			</td>
			</tr>
			<tr>
				<td><span class="inline"><a href="edit/sjefen6" class="button">basso</a></span></td>
				<!-- Only for Administrators -->
				<td>
					<select>
						<option value="-1">Disabled</option>
						<option value="0" selected>User</option>
						<option value="100">Administrator</option>
					</select>
      			</td>
      			<!-- end only -->
      			<td></td>
      			<td></td>
      			<td>
      				<a href="export/sjefen6" class="button">Export</a>
      			</td>
			</tr>
		</tbody>
	</table>
</div>
</div>
<?php 
include('footer.phtml'); 
?>