<?php 
include('header.phtml');
include('nav.phtml');
?>
<div class="row">
<div class="small-12 medium-6 medium-offset-3 columns">
	<form id="edituser-form"  method="POST">
		<fieldset>
			<legend>Edit user</legend>
			<div class="small-12">
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Username</label>
					</div>
					<div class="small-9 columns">
						<input type="text" name="username" placeholder="cc-user" value="<?=$username?>" disabled>
					</div>
				</div>
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Name</label>
					</div>
					<div class="small-9 columns">
					<input type="text" name="name" placeholder="<?=$name?>" value="">
					</div>
				</div>
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Mail</label>
					</div>
					<div class="small-9 columns">
					<input type="email" name="mail" placeholder="<?=$mail?>" value="">
					</div>
				</div>
				<div class="row">
					<div class="small-3 columns">
						<label for="right-label" class="right inline">Password</label>
					</div>
					<div class="small-9 columns">
						<input type="password" name="password" placeholder="********">
					</div>
				</div>
		</fieldset>
		<input type="submit" class="button" value="Update">
	</form>
</div>
</div>
<?php 
include('footer.phtml'); 
?>
